# Generated by Django 5.1.1 on 2025-05-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0010_booking_email_booking_full_name_booking_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='vip_price',
            field=models.IntegerField(default=4000, verbose_name='Стоимость VIP (₽)'),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP-место'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='price',
            field=models.IntegerField(default=2000, verbose_name='Стоимость (₽)'),
        ),
    ]
